import { JWT } from "google-auth-library";
import { NextResponse } from "next/server";
// Initialize the Google Sheets AP
import { GoogleSpreadsheet } from "google-spreadsheet";

export async function POST(request: Request) {
  try {
    // Extract the form data from the request body
    const json = await request.json();
    console.log(process.env.PRIVATE_KEY, process.env.EMAIL);

    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: process.env.EMAIL,
      key: process.env.PRIVATE_KEY,
      scopes: ["https://www.googleapis.com/auth/spreadsheets"],
    });

    const doc = new GoogleSpreadsheet(
      "<the sheet ID from the url>",
      serviceAccountAuth
    );

    await doc.loadInfo(); // loads document properties and worksheets
    console.log(doc.title);
    await doc.updateProperties({ title: "Contact Portfolio doc" });
    console.log(json);
    // Load the Google Sheets document
    // Select the first sheet
    const sheet = doc.sheetsByIndex[0];

    // Append the form data as a new row in the sheet
    await sheet.addRow({
      Name: json.name,
      Email: json.email,
      Message: json.message,
    });

    let json_response = {
      status: "success",
      data: {
        message: "success",
      },
    };
    return new NextResponse(JSON.stringify(json_response), {
      status: 201,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error:", error);
    let error_response = {
      status: "error",
      message: error.message || "An error occurred",
    };
    return new NextResponse(JSON.stringify(error_response), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}
